### ISSUE TITLE
[Input] New & Update

### ISSUE THREAD

**Issue by dsict** [spaceone-dev/spaceone-design-system#1057]
**Problem** 
- Need a password input component
- Need copy function

**Figma Link** https://www.figma.com/file/IS6P8y1Wn2nfBC4jGlSiya/Components?node-id=4621%3A380436

**Additional Description**
- Add the password input component and copy function before updating service account v2
- A show and hide toggle is required.

Add priority (high / medium / low) label :)
- high: bug, error, critical issues
- medium: scheduled job according to the roadmap
- low: improvement

**Comment by WANZARGEN** [comment]
we moved repository to https://github.com/cloudforet-io/mirinae
