### ISSUE TITLE
[Input Components] Update

### ISSUE THREAD

**Issue by dsict** [spaceone-dev/spaceone-design-system#1058]
**Problem** 
The following components' UI Consistency: text-input, multi-text-input, password-input

**Solution**
Update design for focused state

**Figma Link**
https://www.figma.com/file/IS6P8y1Wn2nfBC4jGlSiya/Components?node-id=10%3A193213

**Comment by WANZARGEN** [comment]
we moved repository to https://github.com/cloudforet-io/mirinae
