### ISSUE TITLE
[badges / badge v1.10.3] green badge color has changed

### ISSUE THREAD

**Issue by heeyoung1332** [spaceone-dev/spaceone-design-system#1079]
** poor readability of green badge color **

** changed color --- green from 600 to 400 & font color from white to gray/900 **

** [Figma](https://www.figma.com/file/IS6P8y1Wn2nfBC4jGlSiya/Components?node-id=10%3A15908) **

 
Priority (medium)

**Comment by WANZARGEN** [comment]
we moved repository to https://github.com/cloudforet-io/mirinae
