### ISSUE TITLE
Created an additional component of 'Search Dropdown'

### ISSUE THREAD

**Issue by heeyoung1332** [spaceone-dev/spaceone-design-system#656]
Created an additional component of 'Search Dropdown' with title, numbers (selected numbers out of total numbers), and a button to finish.

Figma link : https://www.figma.com/file/wq4wSowBcADBuUrMEZLz6i/SpaceONE-Console-Design?node-id=15215%3A314416

**Comment by dsict** [comment]
@heeyoung1332, Could you please add a figma link of the component?
