### ISSUE TITLE
[Data Table] Update slot props

### ISSUE THREAD

**Issue by yuda110** [spaceone-dev/spaceone-design-system#766]
**Describe the bug**
slot으로 받는 `index` 값이 열 index인지 행 index인지 구분하기가 힘듦.
명확한 구분을 위해 `index`라 되어 있는 값들을 `colIndex`와 `rowIndex`이름으로 추가.
`index`는 이후에 삭제.

**Comment by WANZARGEN** [comment]
colIndex, rowIndex 추가 완료.
