### ISSUE TITLE
[Foundation] New Font weight

### ISSUE THREAD

**Issue by h22y25n** [spaceone-dev/spaceone-design-system#834]
**Problem**
Hard to design detailed typography

**Solution**
Add New font-weight `semi-bold`

**Figma / Jira Link**
[Figma - font weight](https://www.figma.com/file/DVwz3WQLLIxWXj4d4W8MQI/Foundation?node-id=17863%3A182891)

**Additional Description**
Typography rules have been changed (to tokenize ready)

**Comment by song2kim** [comment]
Google Fonts does not provide 600 font-weight(semi-bold) of Noto Sans, so we need to discuss it again.

You could check below link that Google Fonts provide only 400,700 font-wight of Noto Sans.
https://fonts.google.com/noto/specimen/Noto+Sans

**Comment by song2kim** [comment]
I will close the pull request as we decided to re-discuss when applying the Pretendard font
