### ISSUE TITLE
[context-menu] Update *Please update this component before updating other input components

### ISSUE THREAD

**Issue by dsict** [spaceone-dev/spaceone-design-system#844]
**Problem** Too many styles and variants

**Solution**
1. Change the default theme's design
2. Integrate multi-selectable types
2. Delete other theme and theme property
3. Delete invalid state (no need more)

**FigmaLink** https://www.figma.com/file/IS6P8y1Wn2nfBC4jGlSiya/Components?node-id=10%3A170721

**Additional Description**
Please update this component before updating other input components.
Because this component is related with other input components(dropdown, search, input, search-dropdown).

**Comment by dsict** [comment]
Does this component include the function to display the keywords that match the search keyword?

**Comment by yuda110** [comment]
@dsict No, only PSearchDropdown has that function.

**Comment by yuda110** [comment]
All solutions were applied in #866. (except **tree type**!)
Tree type takes a lot of time, so we'll do it later.

**Comment by WANZARGEN** [comment]
apply tree

**Comment by WANZARGEN** [comment]
Tree type will be added with other issue.
