### ISSUE TITLE
[Search-Dropdown] Update

### ISSUE THREAD

**Issue by dsict** [spaceone-dev/spaceone-design-system#855]
**Problem** Dropdown is a selection UI, not search UI.

**Solution**
1. Change the parent category: search -> dropdown
   After the change, there will be 2 components (select-dropdown, search-dropdown) in the dropdown.
2. Delete checkbox type
3. Change the type from 'checkbox+title' to 'multi-selectable' 
4. Update design. Refer to the figma link below.

**Figma / Jira Link** 
https://www.figma.com/file/IS6P8y1Wn2nfBC4jGlSiya/Components?node-id=10%3A202958

**Comment by yuda110** [comment]
Almost all issues were applied in #867.
Moving (multiSelectable) tag position will be supported by @song2kim.

**Comment by song2kim** [comment]
Fixed UI of multi-select in PSearchDropdown. Can you please confirm? @dsict

**Comment by dsict** [comment]
No more problems except for the delete button. The arrow should be in the dropdown, even if there is a delete button. Please check again.
