### ISSUE TITLE
"All styles" stylesheet for non-Tailwind projects is prohibitively large?

### ISSUE THREAD

**Issue by sentience** [spaceone-dev/spaceone-design-system#945]
Apologies for dropping into your issues like this, but I'm doing some research towards [our own design system](https://github.com/cultureamp/kaizen-design-system/)'s potential adoption of Tailwind, and I wanted to ask about a small detail of your setup.

In your README, you [advise non-Tailwind projects to import the "all styles" stylesheet](https://github.com/spaceone-dev/spaceone-design-system/blob/beta/README.md#case-1-all-styles) (dist/css/style.css). This file appears to be 8.1MB, which seems prohibitively large.

Do you make use of Tailwind's support for generating only the styles actually used in your source code?

**Comment by WANZARGEN** [comment]
Our design system is still in beta, and currently we do not provide a stylesheet containing only tailwind css for non-Tailwind projects.
Our console project using this design system uses tailwindcss, so there was no such need.
But it's definitely a worthwhile feature, so I'll consider providing it.
Thanks for the suggestion.

**Comment by WANZARGEN** [comment]
we moved repository to https://github.com/cloudforet-io/mirinae
